// [config]
// expect_result: fail
// glsl_version: 1.50
// require_extensions: GL_ARB_compute_shader GL_ARB_gpu_shader_int64 GL_NV_shader_atomic_int64
// [end config]
//
// The extension is supported by the implementation, but it is not enabled in
// the shader.  This should fail to compile.

#version 150
#extension GL_ARB_compute_shader: require
#extension GL_ARB_gpu_shader_int64: require

layout(local_size_x = 32) in;

shared uint64_t val;

void main()
{
	atomicAdd(val, 1UL);
}
