/*
 * Copyright © 2013 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/**
 * \file bgra-errors.c
 *
 * This tests a few error conditions from the ARB_vertex_array_bgra extension.
 */

#include "piglit-util-gl-common.h"

PIGLIT_GL_TEST_CONFIG_BEGIN
	config.supports_gl_compat_version = 10;
	config.window_visual = PIGLIT_GL_VISUAL_RGB | PIGLIT_GL_VISUAL_DOUBLE;
PIGLIT_GL_TEST_CONFIG_END

void
check_invalid_value()
{
	if (!piglit_check_gl_error(GL_INVALID_VALUE))
		piglit_report_result(PIGLIT_FAIL);
}

void
piglit_init(int argc, char **argv)
{
	static GLuint uints[4] = { 255, 0, 0, 127 };
	static GLubyte ubytes[4] = { 255, 0, 0, 127 };

	piglit_require_gl_version(20);
	piglit_require_extension("GL_ARB_vertex_array_bgra");

	/* From the GL_ARB_vertex_array_bgra specification:
	 * "The error INVALID_VALUE is generated by VertexAttribPointer if
	 *  size is BGRA and normalized is FALSE."
	 */
	glVertexAttribPointer(1, GL_BGRA, GL_UNSIGNED_BYTE, GL_FALSE,
			      4 * sizeof(GLubyte), ubytes);
	check_invalid_value();

	/* From the GL_ARB_vertex_array_bgra specification:
	 * "The error INVALID_VALUE is generated when ColorPointer,
	 *  SecondaryPointer, or VertexAttribPointer is called with size
	 *  set to BGRA and type is not UNSIGNED_BYTE."
	 */
	glColorPointer(GL_BGRA, GL_UNSIGNED_INT, 4 * sizeof(GLuint), NULL);
	check_invalid_value();

	glSecondaryColorPointer(GL_BGRA, GL_UNSIGNED_INT,
				4 * sizeof(GLuint), NULL);
	check_invalid_value();

	glVertexAttribPointer(1, GL_BGRA, GL_UNSIGNED_INT, GL_TRUE,
			      4 * sizeof(GLuint), uints);
	check_invalid_value();

	piglit_report_result(PIGLIT_PASS);
}

enum piglit_result
piglit_display(void)
{
	/* Should never get here. */
	return PIGLIT_FAIL;
}
