// [config]
// expect_result: pass
// glsl_version: 1.50
// require_extensions: GL_ARB_enhanced_layouts GL_ARB_compute_shader
// [end config]
//
// From the ARB_enhanced_layouts spec:
//
//    "More than one layout qualifier may appear in a single declaration.
//     Additionally, the same layout-qualifier-name can occur multiple times
//     within a layout qualifier or across multiple layout qualifiers in the
//     same declaration. When the same layout-qualifier-name occurs
//     multiple times, in a single declaration, the last occurrence overrides
//     the former occurrence(s).  Further, if such a layout-qualifier-name
//     will effect subsequent declarations or other observable behavior, it
//     is only the last occurrence that will have any effect, behaving as if
//     the earlier occurrence(s) within the declaration are not present.
//     This is also true for overriding layout-qualifier-names, where one
//     overrides the other (e.g., row_major vs. column_major); only the last
//     occurrence has any effect."
//
// From the ARB_compute_shader spec:
//
//    "[If an input layout qualifier] is declared more than once in
//     the same shader, all those declarations must indicate the same
//     local work-group size; otherwise a compile-time error results."

#version 150
#extension GL_ARB_enhanced_layouts: enable
#extension GL_ARB_compute_shader: enable

layout(local_size_z = 1, local_size_z = 2) in;
layout(local_size_z = 2) in;

void main()
{
}
