// [config]
// expect_result: pass
// glsl_version: 3.30
// require_extensions: GL_ARB_compute_shader
// [end config]
//
// Test the minimum values for gl_MaxComputeWorkGroupCount specified
// in ARB_compute_shader.

#version 330
#extension GL_ARB_compute_shader: enable

layout(local_size_x = 1) in;

void main()
{
  int x[gl_MaxComputeWorkGroupCount.x >= 65535 ? 1 : -1];
  int y[gl_MaxComputeWorkGroupCount.y >= 65535 ? 1 : -1];
  int z[gl_MaxComputeWorkGroupCount.z >= 65535 ? 1 : -1];
}
