// [config]
// expect_result: fail
// glsl_version: 4.50
// require_extensions: GL_NV_compute_shader_derivatives
// [end config]
//
// NV_compute_shader_derivatives says
//
//    The layout qualifier "derivative_group_linearNV" specifies that
//    derivatives in compute shaders are evaluated over groups of four
//    invocations with consecutive gl_LocalInvocationIndex values of the form
//    4x+{0,1,2,3}.  It is a compile-time error if this qualifier is used with a
//    local group size whose total number of invocations is not a multiple of
//    four.

#version 450
#extension GL_NV_compute_shader_derivatives: require

layout(local_size_x = 3, local_size_y = 3) in;
layout(derivative_group_linearNV) in;

void main() {}
