#!/bin/sh

output=$(valgrind --quiet --error-exitcode=1 "$@")
exit_code=$?

# If valgrind is happy, then this test passes, so we substitute a pass
# result in the place of any existing piglit result line.
if [ "$exit_code" = "0" ]; then
    echo "$output" | grep -v '^PIGLIT'
    echo "PIGLIT: {'result': 'pass' }"
    exit 0
fi

# A non-zero exit code could mean either a valgrind error or a failure
# of the underlying test.

# Look for a piglit result of pass in the original output to ensure
# that this is a valgrind error, and if so, return a piglit failure.
if echo "$output" | grep -q '^PIGLIT.*pass'; then
    echo "$output" | grep -v 'PIGLIT'
    echo "PIGLIT: {'result': 'fail' }"
    exit 1
fi

# Otherwise, the underlying test failed, so we simply report a piglit
# skip for this valgrind test.
echo "$output" | grep -v 'PIGLIT'
echo "PIGLIT: {'result': 'skip' }"
exit 0
