static const char passthrough_vertex_shader_source_spv[] =
	"               OpCapability Shader\n"
	"               OpMemoryModel Logical GLSL450\n"
	"               OpEntryPoint Vertex %main \"main\" %pos_in %pos_out\n"
	"               OpDecorate %pos_in Location 0\n"
	"               OpDecorate %pos_out BuiltIn Position\n"
	"       %void = OpTypeVoid\n"
	"  %func_type = OpTypeFunction %void\n"
	"      %float = OpTypeFloat 32\n"
	"    %v4float = OpTypeVector %float 4\n"
	"%_ptr_Input_v4float = OpTypePointer Input %v4float\n"
	"%_ptr_Output_v4float = OpTypePointer Output %v4float\n"
	"     %pos_in = OpVariable %_ptr_Input_v4float Input\n"
	"    %pos_out = OpVariable %_ptr_Output_v4float Output\n"
	"       %main = OpFunction %void None %func_type\n"
	" %main_label = OpLabel\n"
	" %pos_in_val = OpLoad %v4float %pos_in\n"
	"               OpStore %pos_out %pos_in_val\n"
	"               OpReturn\n"
	"               OpFunctionEnd\n";
