// [config]
// expect_result: fail
// glsl_version: 3.30
// require_extensions: GL_ARB_compute_variable_group_size
// [end config]
//
// The ARB_compute_variable_group_size spec says:
//
//     However, the constant "gl_WorkGroupSize" would still be useful for
//     sizing built-in arrays for shaders with a fixed work group size. For
//     example, a shader might want to declare a shared variable with one
//     instance per work group invocation, such as:
//
//     shared float shared_values[gl_WorkGroupSize.x *
//                                gl_WorkGroupSize.y * gl_WorkGroupSize.z];
//
//     Such declarations would be illegal using the input
//     "gl_LocalGroupSizeARB".

#version 330
#extension GL_ARB_compute_variable_group_size: enable

layout(local_size_variable) in;

void main()
{
	uint v[gl_LocalGroupSizeARB.x];
}
