// [config]
// expect_result: fail
// glsl_version: 3.30
// require_extensions: GL_ARB_compute_variable_group_size
// [end config]
//
// From the ARB_compute_variable_group_size spec:
//
//     If a compute shader including a *local_size_variable* qualifier also
//     declares a fixed local group size using the *local_size_x*,
//     *local_size_y*, or *local_size_z* qualifiers, a compile-time error
//     results.

#version 330
#extension GL_ARB_compute_variable_group_size: enable
#extension GL_ARB_compute_shader: enable

layout(local_size_x = 2) in;
layout(local_size_variable) in;

void main()
{
}
