// [config]
// expect_result: fail
// glsl_version: 1.50
// require_extensions: GL_ARB_shading_language_420pack GL_ARB_compute_shader
// [end config]
//
// From the ARB_shading_language_420pack spec:
//
//    "More than one layout qualifier may appear in a single declaration. If
//     the same layout-qualifier-name occurs in multiple layout qualifiers for
//     the same declaration, the last one overrides the former ones."
//
// From the ARB_compute_shader spec:
//
//    "[If an input layout qualifier] is declared more than once in
//     the same shader, all those declarations must indicate the same
//     local work-group size; otherwise a compile-time error results."

#version 150
#extension GL_ARB_shading_language_420pack: enable
#extension GL_ARB_compute_shader: enable

layout(local_size_z = 2) layout(local_size_z = 1) in;
layout(local_size_z = 2) in;

void main()
{
}
